[project]
name = "ch03-coding-attention-mechanisms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.3",
    "torch>=2.5.1",
]
